DROP DATABASE IF EXISTS mycat01;
CREATE DATABASE mycat01;
USE mycat01;
CREATE TABLE customer
(
    id          INT PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '客户ID',
    name        varchar(20)              DEFAULT '' COMMENT '可以姓名',
    phone       varchar(11)              DEFAULT '' COMMENT '客户手机号',
    add_date    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    update_date TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8;

CREATE TABLE item
(
    id          INT PRIMARY KEY AUTO_INCREMENT COMMENT '货物ID',
    value       INT       NOT NULL DEFAULT 0,
    add_date    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8;

DROP DATABASE IF EXISTS mycat02;
CREATE DATABASE mycat02;
USE mycat02;
CREATE TABLE item
(
    id          INT PRIMARY KEY AUTO_INCREMENT COMMENT '货物ID',
    value       INT       NOT NULL DEFAULT 0,
    add_date    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8;

DROP DATABASE IF EXISTS mycat03;
CREATE DATABASE mycat03;
USE mycat03;
CREATE TABLE item
(
    id          INT PRIMARY KEY AUTO_INCREMENT COMMENT '货物ID',
    value       INT       NOT NULL DEFAULT 0,
    add_date    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8;

CREATE TABLE customer_order1
(
    id          INT PRIMARY KEY AUTO_INCREMENT COMMENT '货物ID',
    amount      INT       NOT NULL DEFAULT 0,
    add_date    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8;

CREATE TABLE customer_order2
(
    id          INT PRIMARY KEY AUTO_INCREMENT COMMENT '货物ID',
    amount      INT       NOT NULL DEFAULT 0,
    add_date    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8;

CREATE TABLE customer_order3
(
    id          INT PRIMARY KEY AUTO_INCREMENT COMMENT '货物ID',
    amount      INT       NOT NULL DEFAULT 0,
    add_date    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8;
